CREATE TABLE sensor (
    name varchar(30) PRIMARY KEY);


CREATE TABLE measurement (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value decimal NOT NULL CHECK(value <= 100 AND value >= -100),
    raining BOOLEAN NOT NULL,
    sensor_name int NOT NULL REFERENCES sensor(name) ON DELETE CASCADE,
    measured_at TIMESTAMP NOT NULL );

INSERT INTO sensor(name) VALUES ('Sensor1');

INSERT INTO measurement(value, raining, sensor_name, measured_at)
VALUES (26, true, 'Sensor11-A1', '2022-05-16 20:38:40');

SELECT * FROM sensor;
SELECT * FROM measurement;

TRUNCATE sensor;
TRUNCATE measurement;